### ISSUE TITLE
Remove project.lock.json

### ISSUE THREAD

**Issue by herecydev** [mattridgway/WeatherTest#3]
Should update the .gitignore to remove this. It's not something you would check in.

**Comment by mattridgway** [comment]
I need to get rid of the .vs folder too - just re-installing VS2015

**Comment by herecydev** [comment]
Isn't the `applicationhost.config` something you would want centralized?

**Comment by mattridgway** [comment]
I was under the impression files under .vs were all temporary

**Comment by herecydev** [comment]
I thought that too, but not a web stack developer so unsure of what `applicationhost.config` does. Seems vital though?

**Comment by mattridgway** [comment]
its used for configuration for web service to run the APIs, its automatically generated, and as we don't need any specific setup to get the api's to run, I'm happy to leave it out.

**Comment by herecydev** [comment]
I would imagine the correct way would be to include a `*.config` in `src/` and configure it through middleware.

**Comment by mattridgway** [comment]
I believe its host configuration not application configuration, so would not be used inside your code.
